version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "enhancement"
  # Maintain dependencies for npm packages
  - package-ecosystem: "npm"
    directory: "/src/results"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "enhancement"
  - package-ecosystem: "npm"
    directory: "/src/vote"
    schedule:
      interval: "monthly"
    target-branch: "master"
    labels:
      - "enhancement"
