{{- if .Values.vote.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "voting-app.vote.serviceAccountName" . }}-vote
  labels:
    {{- include "voting-app.vote.labels" . | nindent 4 }}
  {{- with .Values.vote.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.vote.serviceAccount.automount }}
{{- end }}
