apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voting-app.fullname" . }}-postgres
  labels:
    {{- include "voting-app.postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.environment.POSTGRES_PASSWORD | b64enc | quote }}
