apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-postgres
  labels:
    {{- include "voting-app.postgres.labels" . | nindent 4 }}
{{- if .Values.postgres.service.annotations }}
  annotations:
    {{- .Values.postgres.service.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "voting-app.postgres.selectorLabels" . | nindent 4 }}
