apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "voting-app.fullname" . }}-postgres
  labels:
    {{- include "voting-app.postgres.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 5
  serviceName: {{ include "voting-app.fullname" . }}-postgres
  replicas: 1
  minReadySeconds: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    {{/*
    whenScaled: Delete
    */}}
  selector:
    matchLabels:
      {{- include "voting-app.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.postgres.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "voting-app.postgres.labels" . | nindent 8 }}
        {{- with .Values.postgres.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.environment.POSTGRES_DB | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.environment.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "voting-app.fullname" . }}-postgres
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.postgres.storage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.postgres.storage.size }}
