name: Publish Helm Chart

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v4.1.1

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin

      - name: Package Helm chart
        run: |
          helm lint ./helm/voting-app
          helm package ./helm/voting-app

      - name: Push Helm chart
        run: helm push voting-app-*.tgz oci://ghcr.io/${{ github.repository }}
