name: Trivy Scan

on:
  push:
    branches:
      - master

permissions:
  contents: read
  security-events: write

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan:
    name: Scan with Trivy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_name: ["results", "vote"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.service_name }}
          tags: ${{ github.ref_name }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: |
            SERVICE_NAME=${{ matrix.service_name }}
          platforms: |
            linux/amd64
            linux/arm64
          push: false
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.34.0
        with:
          image-ref: ${{ matrix.service_name }}:${{ github.ref_name }}
          format: "sarif"
          output: "trivy-results-${{ matrix.service_name }}.sarif"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: "trivy-results-${{ matrix.service_name }}.sarif"
